In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect('SDOH.db')
main_table = 'Main'
main_query = f"SELECT * FROM {main_table} WHERE QUESTION_ID = '8258'"

In [3]:
df = pd.read_sql_query(main_query, conn)

In [4]:
df['RESULTS'][1]

'Pests (such as bugs, ants or mice)'

In [5]:
dummy_columns = df['RESULTS'].str.get_dummies(';')
id_column = df['ID']
housing_df = pd.concat([id_column, dummy_columns], axis = 1)

In [6]:
column_order = ['ID', 'Pests (such as bugs, ants or mice)', 'Mold', 'Lead paint or pipes', 'Water leaks',
                'Smoke detectors missing or not working', 'Oven or stove not working', 'Lack of heat', 'None of the above']

In [7]:
set(column_order).symmetric_difference(set(dummy_columns.columns))

{'ID',
 'NA',
 'Not asked',
 'Prefer not to answer',
 'Smoke deterctors missing or not working'}

In [8]:
column_order.extend(['NA', 'Not asked', 'Prefer not to answer', 'Smoke deterctors missing or not working'])

In [9]:
housing_df = housing_df.reindex(columns = column_order)
housing_df

,ID,"Pests (such as bugs, ants or mice)",Mold,Lead paint or pipes,Water leaks,Smoke detectors missing or not working,Oven or stove not working,Lack of heat,None of the above,NA,Not asked,Prefer not to answer,Smoke deterctors missing or not working
0,125032,0,0,0,0,0,0,0,1,0,0,0,0
1,79961,1,0,0,0,0,0,0,0,0,0,0,0
2,68678,0,0,0,0,0,0,0,1,0,0,0,0
3,169757,0,0,0,0,0,0,0,1,0,0,0,0
4,36154,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
28169,152458,0,0,0,0,0,0,0,1,0,0,0,0
28170,185238,0,0,0,0,0,0,0,1,0,0,0,0
28171,123024,0,0,0,0,0,0,0,1,0,0,0,0
28172,142784,0,0,0,0,0,0,0,1,0,0,0,0
28173,92173,0,0,0,0,0,0,0,1,0,0,0,0

In [10]:
housing_df['Smoke detectors missing or not working'] = (
    housing_df['Smoke detectors missing or not working'] | housing_df['Smoke deterctors missing or not working'])
housing_df.drop(columns = ['Smoke deterctors missing or not working'], inplace = True)

In [11]:
housing_df['NA'] = housing_df['NA'] | housing_df['Not asked'] | housing_df['Prefer not to answer']
housing_df.drop(columns = ['Not asked', 'Prefer not to answer'], inplace = True)

In [12]:
housing_df

,ID,"Pests (such as bugs, ants or mice)",Mold,Lead paint or pipes,Water leaks,Smoke detectors missing or not working,Oven or stove not working,Lack of heat,None of the above,NA
0,125032,0,0,0,0,0,0,0,1,0
1,79961,1,0,0,0,0,0,0,0,0
2,68678,0,0,0,0,0,0,0,1,0
3,169757,0,0,0,0,0,0,0,1,0
4,36154,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...
28169,152458,0,0,0,0,0,0,0,1,0
28170,185238,0,0,0,0,0,0,0,1,0
28171,123024,0,0,0,0,0,0,0,1,0
28172,142784,0,0,0,0,0,0,0,1,0
28173,92173,0,0,0,0,0,0,0,1,0

In [13]:
housing_df[(housing_df['NA'] == 1) & (housing_df.iloc[:, 1:-1].sum(axis=1) > 0)]

,ID,"Pests (such as bugs, ants or mice)",Mold,Lead paint or pipes,Water leaks,Smoke detectors missing or not working,Oven or stove not working,Lack of heat,None of the above,NA
74,189029,1,1,0,1,0,0,0,0,1
443,132384,0,0,0,0,0,0,0,1,1
548,70433,0,0,0,1,0,0,0,0,1
588,109923,0,0,0,0,0,0,0,1,1
1024,6007,0,0,0,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
26185,80656,0,0,0,0,0,0,0,1,1
27124,108186,0,0,0,0,0,0,0,1,1
27344,58310,0,0,0,0,0,0,0,1,1
27443,6542,1,0,0,0,0,0,0,0,1
27892,167433,0,0,0,0,0,0,0,1,1

In [14]:
housing_df['NA'] = housing_df.apply(lambda row: 1 if (row[1:-1] == 0).all() else 0, axis = 1)

In [15]:
housing_df

,ID,"Pests (such as bugs, ants or mice)",Mold,Lead paint or pipes,Water leaks,Smoke detectors missing or not working,Oven or stove not working,Lack of heat,None of the above,NA
0,125032,0,0,0,0,0,0,0,1,0
1,79961,1,0,0,0,0,0,0,0,0
2,68678,0,0,0,0,0,0,0,1,0
3,169757,0,0,0,0,0,0,0,1,0
4,36154,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...
28169,152458,0,0,0,0,0,0,0,1,0
28170,185238,0,0,0,0,0,0,0,1,0
28171,123024,0,0,0,0,0,0,0,1,0
28172,142784,0,0,0,0,0,0,0,1,0
28173,92173,0,0,0,0,0,0,0,1,0

In [16]:
housing_df.to_sql('HousingProblems', conn, if_exists = 'replace', index = False)

28174

In [17]:
conn.commit()
conn.close()